### ISSUE TITLE
Browser app does not redirect the user to the application root upon "Reset App".

### ISSUE THREAD

**Issue by farscapian** [clams-tech/browser-app#122]
When I click "Reset App" under /settings, the user is directed to http://127.0.0.1/settings rather than the application root.

**Comment by johngribbin** [comment]
@farscapian I can't replicate this. Seems to work on my end!

How are you running the app when this happens?

**Comment by farscapian** [comment]
@johngribbin I was actually using the https://github.com/clams-tech/clams-app-docker app. So perhaps I'm not handling redirects properly over there. Will re-open this issue over there.
