### ISSUE TITLE
Failed to parse LNURL

### ISSUE THREAD

**Issue by pabpas** [clams-tech/browser-app#157]
Payments to lightning addresses always fail with this message. The error appears right after entering the address and clicking Next.

Version 1.7.0

**Comment by aaronbarnardsound** [comment]
Yeah it looks like I messed up our server migration and the http proxy for LNURL requests wasn't working correctly. It should be fixed now, let me know if it looks fixed on your end!

**Comment by pabpas** [comment]
Fixed, thank you!
