### ISSUE TITLE
Console is throwing and error and nothing is loading

### ISSUE THREAD

**Issue by jb55** [clams-tech/browser-app#65]
![Dec12-155100](https://user-images.githubusercontent.com/45598/207184889-c03c00f5-4874-41e9-96dc-11993513266e.png)

wish I could provide more info but there appears to be no other logs and the screen is blank.

**Comment by aaronbarnardsound** [comment]
Actually what version of CLN are you running? I think that this might be to do with calculating balance from the `listfunds.channels` response. We use the `our_amount_msat` value, but I remember on other versions it was a different param.

**Comment by aaronbarnardsound** [comment]
Added some extra error handling and logging in #66. @jb55 if you have a minute could you try our [staging app](https://staging.app.clams.tech) out?. The staging app will log everything to the console so we will be able to better see what is going on.

**Comment by jb55** [comment]
On Mon, Dec 12, 2022 at 06:16:27PM -0800, Aaron wrote:
>Added some extra error handling and logging in #66. @jb55 if you have a minute could you try our [staging app](https://staging.app.clams.tech) out?. The staging app will log everything to the console so we will be able to better see what is going on.

This one works? weird

**Comment by aaronbarnardsound** [comment]
Ok cool then it must be the issue I thought it might be. If you could check the console for logs we can work out what channel param we are missing when calculating the balance.

**Comment by aaronbarnardsound** [comment]
Ah actually we weren't handling a `our_amount_msat` of `0` due to JS coercion, so that PR would fix it. No need to check the logs!

**Comment by aaronbarnardsound** [comment]
Merged in to production #68
